package ventanas;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.annotations.DesignRoot;
import com.vaadin.ui.Button;
import com.vaadin.ui.CheckBox;
import com.vaadin.ui.HorizontalLayout;
import com.vaadin.ui.Label;
import com.vaadin.ui.PasswordField;
import com.vaadin.ui.RadioButtonGroup;
import com.vaadin.ui.TextField;
import com.vaadin.ui.VerticalLayout;
import com.vaadin.ui.declarative.Design;

/** 
 * !! DO NOT EDIT THIS FILE !!
 * 
 * This class is generated by Vaadin Designer and will be overwritten.
 * 
 * Please make a subclass with logic and additional interfaces as needed,
 * e.g class LoginView extends LoginDesign implements View { }
 */
@DesignRoot
@AutoGenerated
@SuppressWarnings("serial")
public class Pag_Administrador_ventana extends VerticalLayout {
	protected Button bCerrarSesion;
	protected HorizontalLayout layoutGrid;
	protected Button bListar;
	protected Button bCrear;
	protected VerticalLayout layoutCrearUsuario;
	protected Label lUsuario;
	protected TextField tUsername;
	protected Label luser;
	protected TextField tEmail;
	protected Label lemail;
	protected HorizontalLayout hPass;
	protected PasswordField tPass;
	protected PasswordField tRepPass;
	protected Label lpass;
	protected CheckBox cActivo;
	protected RadioButtonGroup<java.lang.String> rbotones;
	protected Button botonCrear;
	protected Button botonCancelar;
	protected Label errorLogin5;
	protected Label errorLogin6;
	protected Label errorLogin7;
	protected Label registroOk;
	protected VerticalLayout vModificar;
	protected Label lUsuario1;
	protected TextField tUsername1;
	protected Label luser1;
	protected TextField tEmail1;
	protected Label lemail1;
	protected HorizontalLayout hPass1;
	protected PasswordField tPass1;
	protected PasswordField tRepPass1;
	protected Label lpass1;
	protected CheckBox cActivo1;
	protected RadioButtonGroup<java.lang.String> rbotones1;
	protected Button botonGuardar;
	protected Button botonCancelar1;
	protected Label errorLogin2;
	protected Label errorLogin3;
	protected Label errorLogin4;
	protected Label registroOk1;
	protected Button cancelar;
	protected Button aceptar;

	public Pag_Administrador_ventana() {
		Design.read(this);
	}
}
